version: '3.9'
networks:
  main:
    name: main_network

services:
  frontend:
    container_name: frontend
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - main
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    # ports:
    #   - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - main
  reverse:
    container_name: proxy-server
    hostname: proxy-server
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - <path/to/your/config>:/etc/nginx
      - <path/to/your/certs>:/etc/ssl/private

